# Generated by Django 3.0.5 on 2020-04-30 16:22

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_1", models.CharField(max_length=30)),
                ("player_2", models.CharField(max_length=30)),
                (
                    "board",
                    models.TextField(
                        default=games.board_utils.board_generator(
                            games.models.BOARD_SIZE
                        )
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
            ],
        ),
    ]
