# Generated by Django 3.0.5 on 2020-05-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_move'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='game',
            name='started',
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.TextField(default=''),
        ),
    ]
